version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientcheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j0kqrowlroub"
s3_prefix = "patientcheckout"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
