version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myfirstapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j0kqrowlroub"
s3_prefix = "myfirstapp"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
